/** FrameConsumer Module integrates with a named pipe generated by the Producer module written in Python. 
*/
class FrameConsumer
{
private:
    HANDLE hPipe;
    char buffer[1024];
    DWORD bytesRead;
    char* pipeName = R"(\\.\\pipe\\MyNamedPipe)";

public:
    /** Connect to the named pipe upon instantiation of FrameConsumer.
     * @param name Directory to the named pipe. Example: `R"(\\.\\pipe\\MyNamedPipe)"`
     */
    FrameConsumer(char* name);

    /** Close from named pipe and cleanup.
     */
    ~FrameConsumer();

    /** Consume the bytestring written in the named pipe.
     * 
     */
    char* readFrame();
};